# version: '3.7'
# services:
#   postgres:
#     image: postgres:13
#     container_name: postgres_db
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_DB: postgresdb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: '123'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:

version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres: